kind: ConfigMap
apiVersion: v1
metadata:
  name: metal3-config
  namespace: openshift-machine-api
data:
  http_port: "6180"
  provisioning_interface: "${PROVISIONING_INTERFACE}"
  provisioning_ip: "${PROVISIONING_ADDRESS}/24"
  dhcp_range: "172.22.0.10,172.22.0.100"
  deploy_kernel_url: "http://${PROVISIONING_ADDRESS}:6180/images/ironic-python-agent.kernel"
  deploy_ramdisk_url: "http://${PROVISIONING_ADDRESS}:6180/images/ironic-python-agent.initramfs"
  ironic_endpoint: "http://${PROVISIONING_ADDRESS}:6385/v1/"
  ironic_inspector_endpoint: "http://${PROVISIONING_ADDRESS}:5050/v1/"
  cache_url: "${CACHE_URL}"
  rhcos_image_url: "${RHCOS_IMAGE_URL}"
